/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../../../../../../../../../../android-ndk-r15c/sysroot/usr/include/jni.h"
#include "com_example_week5_JNIClass.h"
/* Header for class com_example_week5_JNIClass */

#ifndef _Included_com_example_week5_JNIClass
#define _Included_com_example_week5_JNIClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_week5_JNIClass
 * Method:    getNumString
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
extern "C" JNIEXPORT jstring JNICALL Java_com_example_week5_JNIClass_getNumString
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
